# Generated by Django 4.2 on 2023-06-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
