# Generated by Django 4.2 on 2023-06-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0002_cartdb_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Second_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Phone_Number', models.IntegerField(blank=True, null=True)),
                ('District', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
