# Generated by Django 4.2 on 2023-06-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0003_checkdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrationdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Nmae', models.CharField(blank=True, max_length=50, null=True)),
                ('Password', models.IntegerField(blank=True, null=True)),
                ('Email_ID', models.EmailField(blank=True, max_length=254, null=True)),
                ('Phone_Number', models.IntegerField(blank=True, null=True)),
                ('Profile_Image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
