# Generated by Django 4.2 on 2023-06-15 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0004_registrationdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdb',
            old_name='User_Nmae',
            new_name='User_Name',
        ),
    ]
