# Generated by Django 4.2 on 2023-05-14 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productdb',
            new_name='categorydb',
        ),
    ]
